sensu:
    description: "Sensu alerts"
    message:
        classification:
            CRITICAL: ["error", "failure"]
            WARNING: ["warning"]
        exclude: ["keepalive"]
        enrichments:
            - IF: "CheckDisk"
              THEN: "@dylan {} (enrichment added, have a :beer:)"
            - IF: "foo"
              THEN: "test: {}"
        routes:
            - IF: "bytes"
              THEN: "apitests"
    title:
        enrichments:
            - IF: "example"
              THEN: "THEY'RE ENRICHING THE BEERS CHARLIE: {}"

